Lab2
angietune/EPAMLabs_04_21 pull request #2
Opened 2021-04-26 11:10 UTC by angietune

Хотела еще проставить стоимость страницы и количество и выводить цену, но не получилось.... Но так тоже все работает )

2021-04-27 09:52 UTC, NikitaVarchenko requested changes
Нужен abstract класс

2021-04-27 09:52 UTC, NikitaVarchenko commented on PrintingProduct.cs
> +    public class PrintingProduct
Классы лучше в разные файлы разнести

2021-04-27 10:23 UTC, angietune commented on PrintingProduct.cs
> +    public class PrintingProduct
У меня вроде бы все классы в отдельных файлах. Абстрактный класс PrintingProduct.

2021-05-04 12:00 UTC, NikitaVarchenko requested changes

2021-05-04 12:00 UTC, NikitaVarchenko commented on PrintingProduct.cs
> +    public class PrintingProduct
В этом файле класс PrintingProduct и MainClass

2021-05-04 13:24 UTC, NikitaVarchenko commented on PrintingProduct.cs
> +    public class PrintingProduct
Нужно учесть это в след. работах. задание принял

2021-05-04 13:24 UTC, merged